name: J2me build for ant

on:
  push:
    tags:
      - '*'
      
  workflow_dispatch:
    inputs:
      j2mesrc:
        description: 'J2me src dir'
        default: '/home/runner/work/buildJ2me/buildJ2me/J2meSrc/Jimm_Aspro'
      artifactdir:
        description: 'Directory j2me compile jar'
        default: '/home/runner/work/buildJ2me/buildJ2me/J2meSrc/Jimm_Aspro'
# ${{ github.event.inputs.j2mesrc}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8

# Runs a set of commands using the runners shell
    - name: Run maven script
    - uses: guillonapa/action-maven-cli/jdk8@master
      with:
        lifecycle: 'clean package test'


        
    - uses: cedx/setup-ant@main
      with:
          optional-tasks: true

#    - name: Setup Android SDK
#      uses: android-actions/setup-android@v3
    
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"


    - name: build samples
      run: |
               sudo dpkg --add-architecture i386
               sudo apt-get update
               sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386 libxt6:i386
               for x in `ls ./bin`
               do
               chmod +x ./bin/$x
               done
               cd ${{ github.event.inputs.j2mesrc}}
               ant dist-all
      
    - uses: actions/upload-artifact@v4
      with:
        name: J2me-build-${{ steps.slug.outputs.sha8 }}
        path: |
                  ${{ github.event.inputs.artifactdir}}
