name: Android build for ant

on:
  push:
    tags:
      - '*'
      
  workflow_dispatch:
    inputs:
      androidsrc:
        description: 'Android build dir'
        default: '/home/runner/work/buildJ2me/buildJ2me/J2meSrc/Jimm_Aspro'
      artifactdir:
        description: 'Artifaction der zipped'
        default: '/home/runner/work/buildJ2me/buildJ2me/J2meSrc/Jimm_Aspro/android'
# ${{ github.event.inputs.j2mesrc}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

        
    - uses: cedx/setup-ant@main
      with:
          optional-tasks: true

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
            cmdline-tools-version: 9123335

    - name: Install SDK tools 25.2.5
      run: |
              wget  https://dl.google.com/android/repository/tools_r25.2.5-linux.zip
              /usr/bin/unzip -o -q /home/runner/work/buildJ2me/buildJ2me/tools_r25.2.5-linux.zip
              sudo  cp -r /home/runner/work/buildJ2me/buildJ2me/tools /usr/local/lib/android/sdk/

#    - uses: actions/upload-artifact@v4
#      with:
#        name: androidSdk-zipped
#        path: |
#                   /usr/local/lib/android/sdk/
    
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"


    - name: build samples
      run: |
               sudo dpkg --add-architecture i386
               sudo apt-get update
               sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386 libxt6:i386
               for x in `ls ./bin`
               do
               chmod +x ./bin/$x
               done
               cd ${{ github.event.inputs.androidsrc}}
               ant release
      
    - uses: actions/upload-artifact@v4
      with:
        name: Ant-build-Android-${{ steps.slug.outputs.sha8 }}
        path: |
                  ${{ github.event.inputs.artifactdir}}
