name: build artifacts

on:
  push:
    tags:
      - '*'
      
  workflow_dispatch:
    inputs:
      url:
        description: 'Torrent file URL'
        required: true
      compress:
        description: 'Compress File After Download'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

#    - name: Setup Android SDK
#      uses: android-actions/setup-android@v3
    
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"


    - name: build samples
      run: |
            java -version
      
    - uses: actions/upload-artifact@v4
      with:
        name: J2me-build-${{ steps.slug.outputs.sha8 }}
        path: |
               /home/runner/work/buildJ2me/buildJ2me/
