name: build artifacts

on:
  push:
    tags:
      - '*'
      
  workflow_dispatch:
    inputs:
      j2mesrc:
        description: 'J2me src dir'
        default: 'J2meSrc'
      artifactdir:
        description: 'Directory j2me compile jar'
        default: 'J2meSrc'
# ${{ github.event.inputs.MANIFEST_BRANCH }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
        
    - uses: cedx/setup-ant@main
      with:
          optional-tasks: true
    - run: ant -version

#    - name: Setup Android SDK
#      uses: android-actions/setup-android@v3
    
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"


    - name: build samples
      run: |
               sudo dpkg --add-architecture i386
               sudo apt-get update
               sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386 libxt6:i386
               for x in `ls ./bin`
               do
               chmod +x ./bin/$x
               done
               cd ./J2meSrc/Demos/bin/
               chmod +x ./build.sh
               ./build.sh
      
    - uses: actions/upload-artifact@v4
      with:
        name: J2me-build-${{ steps.slug.outputs.sha8 }}
        path: |
               /home/runner/work/buildJ2me/buildJ2me/J2meSrc/
