name: List files

on:
  push:
    tags:
      - '*'
      
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

        
    - uses: cedx/setup-ant@main
      with:
          optional-tasks: true

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
            cmdline-tools-version: 9123335

    - name: Tested Android SDK
      run: |
              wget  https://dl.google.com/android/repository/tools_r25.2.5-linux.zip
              /usr/bin/unzip -o -q /home/runner/work/buildJ2me/buildJ2me/tools_r25.2.5-linux.zip
              sudo ls

#    - uses: actions/upload-artifact@v4
#      with:
#        name: androidSdk-zipped
#        path: |
#                   /usr/local/lib/android/sdk/
                  
                  
        
#    - uses: actions/upload-artifact@v4
#      with:
#        name: SDK Zipped
#        path: /home/runner/work/buildJ2me/buildJ2me/J2meSrc/toolssdk.zip
 
