name: List files

on:
  push:
    tags:
      - '*'
      
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
          - uses: cedx/setup-ant@main
            with:
               optional-ta,sks: true
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
            cmdline-tools-version: 9123335
            
    
#     - name: ListFiles
#            run: |
#                  ls /opt/hostedtoolcache/ant/1.10.14/x64/lib
                  
          - uses: actions/upload-artifact@v4
            with:
                 name: ant-libDump
                 path: |
                          /usr/local/lib/android/sdk/
 
