name: List files

on:
  push:
    tags:
      - '*'
      
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
          - uses: cedx/setup-ant@main
            with:
               optional-tasks: true

          - name: ListFiles
            run: |
                  ls /opt/hostedtoolcache/ant/1.10.14/x64/lib
